repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-executables-have-shebangs
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
     # - id: go-vet
     # - id: go-vet-mod
      - id: go-fmt
      - id: go-fmt-repo
     # - id: golangci-lint
#      - id: golangci-lint-mod
#      - id: golangci-lint-pkg
#      - id: golangci-lint-repo-mod
#      - id: golangci-lint-repo-pkg
